# Generated by Django 3.2.6 on 2022-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=555)),
                ('students', models.CharField(max_length=555)),
                ('modern_labs', models.CharField(max_length=555)),
                ('teacher', models.CharField(max_length=555)),
            ],
            options={
                'verbose_name': 'statistics',
                'verbose_name_plural': 'statistics',
            },
        ),
    ]
